# Generated by Django 5.2.17 on 2026-08-18 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refill_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['size_kg'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCylinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cylinders', to=settings.AUTH_USER_MODEL)),
                ('cylinder_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_units', to='cylinders.cylindertype')),
            ],
        ),
    ]
