// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQfw7aMSehoFTJ6ELNRm2QrqykG53Z6c',
    appId: '1:879575722711:web:60996a7abcdebf30a8de92',
    messagingSenderId: '879575722711',
    projectId: 'tech-solutions-3d0b6',
    authDomain: 'tech-solutions-3d0b6.firebaseapp.com',
    storageBucket: 'tech-solutions-3d0b6.firebasestorage.app',
    measurementId: 'G-TEBS3KS79Z',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRiRqXZiAViNfYC5V4Tl0PSEw_3Sl5vHU',
    appId: '1:879575722711:ios:1abb587057ee37d9a8de92',
    messagingSenderId: '879575722711',
    projectId: 'tech-solutions-3d0b6',
    storageBucket: 'tech-solutions-3d0b6.firebasestorage.app',
    iosBundleId: 'com.yourcompany.gasCylinderApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRiRqXZiAViNfYC5V4Tl0PSEw_3Sl5vHU',
    appId: '1:879575722711:ios:1abb587057ee37d9a8de92',
    messagingSenderId: '879575722711',
    projectId: 'tech-solutions-3d0b6',
    storageBucket: 'tech-solutions-3d0b6.firebasestorage.app',
    iosBundleId: 'com.yourcompany.gasCylinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQfw7aMSehoFTJ6ELNRm2QrqykG53Z6c',
    appId: '1:879575722711:web:60996a7abcdebf30a8de92',
    messagingSenderId: '879575722711',
    projectId: 'tech-solutions-3d0b6',
    authDomain: 'tech-solutions-3d0b6.firebaseapp.com',
    storageBucket: 'tech-solutions-3d0b6.firebasestorage.app',
    measurementId: 'G-TEBS3KS79Z',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeP_w40o-GKJAYZw1uASnsDH1-7bsLYIc',
    appId: '1:879575722711:android:667f6225523a7285a8de92',
    messagingSenderId: '879575722711',
    projectId: 'tech-solutions-3d0b6',
    storageBucket: 'tech-solutions-3d0b6.firebasestorage.app',
  );
}
